// app/frontend/pdv/components/CustomerSelect.svelte
<script lang="ts">
  import type { Action } from "svelte/action";
  import type { Customer } from "../lib/types";
  import Choices from "choices.js";

  let {
    customers,
    selectedCustomerId = $bindable(),
  }: { customers: Customer[]; selectedCustomerId: number | null } = $props();

  let choices: Choices;

  const initChoices: Action = (node) => {
    choices = new Choices("#customer-select", {
      searchEnabled: true,
      placeholderValue: "Select a customer",
      removeItemButton: true,
      renderChoiceLimit: 5,
    });

    return {
      destroy() {
        choices.destroy();
      },
    };
  };

  $effect(() => {
    if (choices) {
      choices.setChoices(
        customers.map((customer) => ({
          value: customer.id,
          label: customer.name,
        }))
      );
    }
  });
</script>

<div>
  <select
    use:initChoices
    id="customer-select"
    class=""
    bind:value={selectedCustomerId}
  >
  </select>
</div>

// app/frontend/pdv/components/CustomerSelect.vue
<script setup lang="ts">
import { onBeforeMount, onBeforeUnmount, onMounted, watchEffect } from "vue";
import type { Customer } from "../lib/types";
import { customers, selectedCustomerId } from "../lib/saleStore";
import Choices from "choices.js";

let choices: Choices;

onMounted(() => {
  choices = new Choices("#customer-select", {
    searchEnabled: true,
    placeholderValue: "Select a customer",
    removeItemButton: true,
    renderChoiceLimit: 5,
  });

  watchEffect(() => {
    choices.setChoices(
      customers.value.data.map((customer) => ({
        value: customer.id,
        label: customer.name,
      }))
    );
  })

  onBeforeUnmount(() => {
    choices.destroy();
  })
})
</script>

<template>
  <div>
    <select id="customer-select" v-model="selectedCustomerId">
    </select>
  </div>
</template>
