// app/frontend/pdv/components/Header.svelte
<script lang="ts">
</script>

<header class="p-3 text-bg-primary">
  <div class="dropdown">
    <button
      class="btn btn-secondary dropdown-toggle"
      type="button"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      Mais
    </button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="/">Home</a></li>
      <li><a class="dropdown-item" href="/products">Produtos</a></li>
      <li><a class="dropdown-item" href="/fiscal_documents">Vendas</a></li>
    </ul>
  </div>
</header>

// app/frontend/pdv/components/Header.vue
<template>
  <header class="p-3 text-bg-primary">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Mais
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/">Home</a></li>
        <li><a class="dropdown-item" href="/products">Produtos</a></li>
        <li><a class="dropdown-item" href="/fiscal_documents">Vendas</a></li>
      </ul>
    </div>
  </header>
</template>
